name: CI
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build web
        run: |
          cd web
          npm install
          npm run build
      - name: Build server
        run: |
          cd server
          go version
          go build ./...
